// Contenido del módulo «EMAs». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Emas() {
  return (
    <>
      <article className="lesson" id="ema-formula">{" "}<h3><span className="ln">{"9.1"}</span>{"SMA vs EMA: ¿cuánto pesa cada vela?"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"SMA(N)"}</strong>{" = suma de los últimos N cierres / N. Todas las velas pesan igual (1/N) y la vela N+1 deja de contar de golpe."}</li><li><strong>{"EMA(N)"}</strong>{": "}<span className="mono">{"EMA = α × cierre + (1 − α) × EMA anterior"}</span>{", con "}<span className="mono">{"α = 2 / (N + 1)"}</span>{". Se arranca con la SMA de las primeras N velas. El peso de cada vela anterior decae de forma exponencial."}</li><li>{"Ambas van "}<strong>{"con retraso"}</strong>{" respecto al precio: es el precio de suavizar."}</li></ul>{" "}</div>{" "}<div className="fig">{" "}<div className="controls"><div className="grp"><span className="lbl">{"Periodo N"}</span><input type="range" id="ew-n" min="3" max="50" defaultValue="20" /><span className="val" id="ew-n-v">{"20"}</span></div></div>{" "}<div className="chart-host" id="fig-ema-w" />{" "}<div className="legend"><span><i className="box" style={{"background":"var(--text-2)"}} />{"SMA: peso igual"}</span><span><i className="box" style={{"background":"var(--c-range)"}} />{"EMA: peso que decae"}</span></div>{" "}<div className="explain" id="ew-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="ema-formula" /></article>
      <article className="lesson" id="ema-lab">{" "}<h3><span className="ln">{"9.2"}</span>{"Laboratorio de medias"}</h3>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Escenario"}</span>{" "}<div className="seg" data-key="sc"><button className="on" data-v="trend">{"Tendencia"}</button><button data-v="range">{"Lateral"}</button><button data-v="rev">{"Giro"}</button></div>{" "}<span className="lbl">{"Tipo"}</span>{" "}<div className="seg" data-key="ty"><button className="on" data-v="ema">{"EMA"}</button><button data-v="sma">{"SMA"}</button></div>{" "}<button className="btn" id="el-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="controls">{" "}<label className="grp"><input type="checkbox" className="el-on" data-k="f" defaultChecked /><span className="lbl">{"Rápida"}</span><input type="range" className="el-n" data-k="f" min="3" max="30" defaultValue="9" /><span className="val" id="el-f-v">{"9"}</span></label>{" "}<label className="grp"><input type="checkbox" className="el-on" data-k="s" defaultChecked /><span className="lbl">{"Lenta"}</span><input type="range" className="el-n" data-k="s" min="10" max="60" defaultValue="21" /><span className="val" id="el-s-v">{"21"}</span></label>{" "}<label className="grp"><input type="checkbox" className="el-on" data-k="l" defaultChecked /><span className="lbl">{"Larga"}</span><input type="range" className="el-n" data-k="l" min="30" max="120" defaultValue="50" /><span className="val" id="el-l-v">{"50"}</span></label>{" "}</div>{" "}<div className="chart-host" id="fig-ema-lab" />{" "}<div className="legend" id="el-legend" />{" "}<div className="readout" id="el-stats" />{" "}<div className="explain" id="el-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="ema-lab" /></article>
      <article className="lesson" id="ema-usos">{" "}<h3><span className="ln">{"9.3"}</span>{"Cómo se usan"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Dirección de la tendencia:"}</strong>{" precio por encima de una media larga (50 o 200) y la media con pendiente positiva = sesgo alcista."}</li><li><strong>{"Soporte / resistencia dinámicos:"}</strong>{" en tendencias sanas, los retrocesos suelen frenarse cerca de la EMA 20/21."}</li><li><strong>{"Cruces:"}</strong>{" la rápida cruza por encima de la lenta (cruce alcista) o por debajo (bajista). Llegan tarde por naturaleza y en rangos dan muchos \"latigazos\" (prueba el escenario Lateral)."}</li><li><strong>{"Separación:"}</strong>{" si el precio se aleja mucho de la media, el movimiento está \"estirado\" y es común un retroceso hacia ella."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="ema-usos" /></article>
      <article className="lesson" id="ema-periodos">{" "}<h3><span className="ln">{"9.4"}</span>{"Periodos populares"}</h3>{" "}<div style={{"overflowX":"auto"}}>{" "}<table className="t wide"><thead><tr><th>{"Periodos"}</th><th>{"Uso habitual"}</th></tr></thead><tbody><tr><td>{"EMA 9 / 21"}</td><td>{"Corto plazo e intradía: ritmo de la tendencia y retrocesos."}</td></tr><tr><td>{"EMA 20 / 50"}</td><td>{"Swing trading: tendencia de medio plazo."}</td></tr><tr><td>{"Media 200"}</td><td>{"Largo plazo: la \"frontera\" entre mercado alcista y bajista que vigila casi todo el mundo."}</td></tr><tr><td>{"50 / 200"}</td><td>{"\"Cruce dorado\" (50 cruza por encima de 200) y \"cruce de la muerte\" (por debajo). Clásicamente con SMA."}</td></tr></tbody></table>{" "}</div>{" "}<div className="rd-sentinel" data-l="ema-periodos" /></article>
      <article className="lesson" id="ema-errores">{" "}<h3><span className="ln">{"9.5"}</span>{"Errores comunes"}</h3>{" "}<div className="callout err"><h5>{"Operar cruces en rangos"}</h5>{"En mercados laterales las medias se entrelazan y cada cruce es una señal falsa."}</div>{" "}<div className="callout err"><h5>{"Esperar que la media \"prediga\""}</h5>{"Una media resume el pasado. Confirma la tendencia; no anticipa giros."}</div>{" "}<div className="callout err"><h5>{"Acumular demasiadas medias"}</h5>{"Cinco medias distintas no dan cinco veces más información: dan más ruido visual."}</div>{" "}<div className="rd-sentinel" data-l="ema-errores" /></article>
      <div id="emas-quiz" />
    </>
  );
}
