// Contenido del módulo «Estocástico». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Estocastico() {
  return (
    <>
      <article className="lesson" id="sto-que">{" "}<h3><span className="ln">{"11.1"}</span>{"Qué mide: la posición del cierre en el rango"}</h3>{" "}<div className="prose">{" "}<p style={{"fontFamily":"var(--mono)","color":"var(--strong)"}}>{"%K = 100 × (Cierre − Mínimo de N) / (Máximo de N − Mínimo de N)"}</p>{" "}<p>{"Con N = 14: si el cierre está justo en el máximo de las últimas 14 velas, %K = 100; si está en el mínimo, %K = 0; a mitad del rango, 50. La idea de Lane: en tendencias alcistas los cierres tienden a quedar cerca de la parte alta del rango, y en bajistas cerca de la parte baja."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls"><div className="grp"><span className="lbl">{"Cierre de la última vela"}</span><input type="range" id="sb-c" min="0" max="100" defaultValue="80" style={{"width":"220px"}} /></div></div>{" "}<div className="chart-host" id="fig-sto-box" />{" "}<div className="explain" id="sb-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="sto-que" /></article>
      <article className="lesson" id="sto-tipos">{" "}<h3><span className="ln">{"11.2"}</span>{"Rápido, lento y completo"}</h3>{" "}<div style={{"overflowX":"auto"}}>{" "}<table className="t wide"><thead><tr><th>{"Versión"}</th><th>{"%K"}</th><th>{"%D"}</th><th>{"Notación típica"}</th></tr></thead><tbody><tr><td><strong>{"Rápido"}</strong></td><td>{"El %K \"crudo\" de la fórmula"}</td><td>{"Media de 3 del %K"}</td><td>{"14, 1, 3"}</td></tr><tr><td><strong>{"Lento"}</strong></td><td>{"Media de 3 del %K crudo"}</td><td>{"Media de 3 del %K lento"}</td><td>{"14, 3, 3"}</td></tr><tr><td><strong>{"Completo"}</strong></td><td>{"Suavizado configurable"}</td><td>{"Periodo configurable"}</td><td>{"N, suavizado %K, %D"}</td></tr></tbody></table>{" "}</div>{" "}<div className="prose"><p>{"El rápido es muy nervioso; por eso la mayoría usa el lento (14, 3, 3), que es el que verás por defecto en muchas plataformas. Ojo: cada plataforma nombra las líneas a su manera; revisa qué significa cada número."}</p></div>{" "}<div className="rd-sentinel" data-l="sto-tipos" /></article>
      <article className="lesson" id="sto-lab">{" "}<h3><span className="ln">{"11.3"}</span>{"Laboratorio del estocástico"}</h3>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Escenario"}</span>{" "}<div className="seg" data-key="sc"><button className="on" data-v="range">{"Lateral"}</button><button data-v="up">{"Tendencia alcista"}</button><button data-v="bear">{"Divergencia bajista"}</button><button data-v="bull">{"Divergencia alcista"}</button></div>{" "}<button className="btn" id="sl-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"N"}</span><input type="range" id="sl-n" min="5" max="21" defaultValue="14" style={{"width":"110px"}} /><span className="val" id="sl-n-v">{"14"}</span></div>{" "}<div className="grp"><span className="lbl">{"Suavizado %K"}</span><input type="range" id="sl-k" min="1" max="5" defaultValue="3" style={{"width":"90px"}} /><span className="val" id="sl-k-v">{"3"}</span></div>{" "}<div className="grp"><span className="lbl">{"%D"}</span><input type="range" id="sl-d" min="1" max="5" defaultValue="3" style={{"width":"90px"}} /><span className="val" id="sl-d-v">{"3"}</span></div>{" "}<button className="btn" data-sp="14,1,3">{"Rápido 14,1,3"}</button>{" "}<button className="btn" data-sp="14,3,3">{"Lento 14,3,3"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-sto-lab" />{" "}<div className="legend"><span><i style={{"background":"var(--c-range)"}} />{"%K"}</span><span><i style={{"background":"var(--c-liq)"}} />{"%D"}</span><span>{"▲ %K cruza sobre %D en sobreventa · ▼ cruza bajo %D en sobrecompra"}</span></div>{" "}<div className="readout" id="sl-stats" />{" "}<div className="explain" id="sl-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="sto-lab" /></article>
      <article className="lesson" id="sto-senales">{" "}<h3><span className="ln">{"11.4"}</span>{"Señales"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Zonas 80 / 20:"}</strong>{" convención habitual de sobrecompra y sobreventa (cierre en el 20% superior o inferior del rango)."}</li><li><strong>{"Cruces %K / %D:"}</strong>{" el cruce de %K por encima de %D en zona de sobreventa (▲) o por debajo en sobrecompra (▼). Más fiables a favor de la tendencia mayor."}</li><li><strong>{"Divergencias:"}</strong>{" Lane les daba mucha importancia; se leen igual que en el RSI."}</li><li><strong>{"Estocástico \"pegado\":"}</strong>{" en tendencias fuertes puede quedarse sobre 80 (o bajo 20) muchas velas. No es una señal de giro: es fuerza."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="sto-senales" /></article>
      <article className="lesson" id="sto-rsi">{" "}<h3><span className="ln">{"11.5"}</span>{"Estocástico vs RSI"}</h3>{" "}<div style={{"overflowX":"auto"}}>{" "}<table className="t wide"><thead><tr><th /><th>{"Estocástico"}</th><th>{"RSI"}</th></tr></thead><tbody><tr><td>{"Qué compara"}</td><td>{"El cierre con el rango (máximo–mínimo) de N velas"}</td><td>{"El tamaño medio de las subidas con el de las bajadas"}</td></tr><tr><td>{"Sensibilidad"}</td><td>{"Alta: más señales y más ruido"}</td><td>{"Menor: más suave"}</td></tr><tr><td>{"Niveles típicos"}</td><td>{"80 / 20"}</td><td>{"70 / 30"}</td></tr><tr><td>{"Mejor entorno"}</td><td>{"Rangos y retrocesos dentro de tendencia"}</td><td>{"Momentum general y divergencias"}</td></tr></tbody></table>{" "}</div>{" "}<div className="rd-sentinel" data-l="sto-rsi" /></article>
      <div id="estocastico-quiz" />
    </>
  );
}
