// Contenido del módulo «Estructura de mercado». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Estructura() {
  return (
    <>
      <article className="lesson" id="est-swings">{" "}<h3><span className="ln">{"4.1"}</span>{"Swings: los puntos de giro"}</h3>{" "}<div className="prose">{" "}<p>{"Un "}<strong>{"swing high"}</strong>{" (máximo oscilante) es una vela cuyo máximo es mayor que el de las N velas a cada lado. Un "}<strong>{"swing low"}</strong>{", al revés. N es la "}<em>{"sensibilidad"}</em>{": con N pequeño verás muchos giros (estructura interna, el \"ruido\"); con N grande, solo los importantes (estructura principal). No hay un N correcto: depende de la temporalidad y de lo que quieras operar."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="est-swings" /></article>
      <article className="lesson" id="est-tendencia">{" "}<h3><span className="ln">{"4.2"}</span>{"Tendencia según la estructura"}</h3>{" "}<div className="cols">{" "}<div className="callout tip-c"><h5>{"Alcista"}</h5>{"Máximos más altos ("}<strong>{"HH"}</strong>{", higher high) y mínimos más altos ("}<strong>{"HL"}</strong>{", higher low)."}</div>{" "}<div className="callout err"><h5>{"Bajista"}</h5>{"Máximos más bajos ("}<strong>{"LH"}</strong>{", lower high) y mínimos más bajos ("}<strong>{"LL"}</strong>{", lower low)."}</div>{" "}</div>{" "}<div className="prose"><p>{"Si la secuencia se mezcla (HH con LL, o máximos y mínimos parecidos), el mercado está en "}<strong>{"rango"}</strong>{". La tendencia sigue \"viva\" mientras se respete el último mínimo relevante (en alcista) o el último máximo relevante (en bajista)."}</p></div>{" "}<div className="rd-sentinel" data-l="est-tendencia" /></article>
      <article className="lesson" id="est-bos">{" "}<h3><span className="ln">{"4.3"}</span>{"BOS y CHoCH"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"BOS (Break of Structure, ruptura de estructura):"}</strong>{" el precio "}<em>{"cierra"}</em>{" más allá del último swing "}<strong>{"a favor"}</strong>{" de la tendencia (supera el último máximo en alcista). Confirma que la tendencia continúa."}</li><li><strong>{"CHoCH (Change of Character, cambio de carácter)"}</strong>{" o MSS: el primer cierre más allá del último swing "}<strong>{"en contra"}</strong>{" de la tendencia (en alcista, perder el último mínimo más alto). Es la primera señal de que la tendencia puede estar cambiando."}</li></ul>{" "}<p>{"Aquí se usa el "}<strong>{"cierre"}</strong>{" para confirmar las rupturas: una mecha que supera el nivel y vuelve es un barrido de liquidez, no una ruptura."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="est-bos" /></article>
      <article className="lesson" id="est-lab">{" "}<h3><span className="ln">{"4.4"}</span>{"Laboratorio de estructura"}</h3>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"Sensibilidad (N velas a cada lado)"}</span><input type="range" id="est-n" min="2" max="8" defaultValue="3" /><span className="val" id="est-n-v">{"3"}</span></div>{" "}<div className="grp"><span className="lbl">{"Temporalidad"}</span><div className="seg" data-key="tf"><button className="on" data-v="1">{"Base"}</button><button data-v="3">{"×3 (mayor)"}</button></div></div>{" "}<button className="btn" id="est-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="controls">{" "}<label className="grp"><input type="checkbox" className="est-l" defaultValue="lab" defaultChecked />{" HH / HL / LH / LL"}</label>{" "}<label className="grp"><input type="checkbox" className="est-l" defaultValue="bos" defaultChecked />{" BOS / CHoCH"}</label>{" "}<label className="grp"><input type="checkbox" className="est-l" defaultValue="sw" />{" Mínimo fuerte / máximo débil"}</label>{" "}<label className="grp"><input type="checkbox" className="est-l" defaultValue="bg" defaultChecked />{" Fondo según tendencia"}</label>{" "}</div>{" "}<div className="chart-host" id="fig-est" />{" "}<div className="legend"><span><i className="box" style={{"background":"var(--c-up)"}} />{"Tramo alcista"}</span><span><i className="box" style={{"background":"var(--c-down)"}} />{"Tramo bajista"}</span><span><i className="dash" style={{"borderColor":"var(--text-2)"}} />{"BOS"}</span><span><i className="dash" style={{"borderColor":"var(--c-liq)"}} />{"CHoCH"}</span></div>{" "}<div className="readout" id="est-stats" />{" "}<div className="explain" id="est-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="est-lab" /></article>
      <article className="lesson" id="est-fuerte">{" "}<h3><span className="ln">{"4.5"}</span>{"Máximos y mínimos fuertes y débiles"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Mínimo fuerte"}</strong>{" (en tendencia alcista): el mínimo desde el que salió el impulso que rompió el máximo (BOS). Es el nivel que \"protege\" la tendencia: si cae, hay CHoCH."}</li><li><strong>{"Máximo débil:"}</strong>{" el último máximo, que todavía no generó nada. Es un objetivo natural: tiene liquidez encima (BSL) y suele terminar barrido o roto."}</li><li>{"En tendencia bajista es al revés: "}<strong>{"máximo fuerte"}</strong>{" y "}<strong>{"mínimo débil"}</strong>{"."}</li></ul>{" "}<p>{"Activa \"Mínimo fuerte / máximo débil\" en el laboratorio para verlos marcados."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="est-fuerte" /></article>
      <article className="lesson" id="est-errores">{" "}<h3><span className="ln">{"4.6"}</span>{"Errores comunes"}</h3>{" "}<div className="callout err"><h5>{"Mezclar temporalidades"}</h5>{"Un \"CHoCH\" en 1 minuto suele ser solo un retroceso dentro de la tendencia de 4H. Define en qué temporalidad lees la estructura principal."}</div>{" "}<div className="callout err"><h5>{"Contar mechas como rupturas"}</h5>{"Una mecha que supera un máximo y cierra dentro es un barrido (liquidez), no un BOS."}</div>{" "}<div className="callout err"><h5>{"Ver tendencia en un rango"}</h5>{"Si los máximos y mínimos se solapan, no fuerces una lectura: el mercado está lateral."}</div>{" "}<div className="rd-sentinel" data-l="est-errores" /></article>
      <div id="estructura-quiz" />
    </>
  );
}
