// Contenido del módulo «Fibonacci». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck
import Link from 'next/link';

export default function Fibo() {
  return (
    <>
      <article className="lesson" id="fb-que">{" "}<h3><span className="ln">{"6.1"}</span>{"De dónde salen los niveles"}</h3>{" "}<div className="prose">{" "}<p>{"La sucesión de Fibonacci (1, 1, 2, 3, 5, 8, 13, 21, 34…) tiene una curiosidad: al dividir un número por el siguiente se tiende a "}<strong>{"0,618"}</strong>{"; por el que está dos lugares más adelante, a "}<strong>{"0,382"}</strong>{"; por el que está a tres, a "}<strong>{"0,236"}</strong>{". A eso se suman dos niveles que no son \"de Fibonacci\" pero todo el mundo usa: el "}<strong>{"0,5"}</strong>{" (la mitad del movimiento) y el "}<strong>{"0,786"}</strong>{" (√0,618)."}</p>{" "}<p>{"La justificación honesta no es matemática ni mística: los niveles funcionan (cuando funcionan) porque "}<strong>{"muchos participantes los miran"}</strong>{" y ponen órdenes ahí. Por eso conviene usar los estándar y no inventar los tuyos."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="fig-title">{"La razón se acerca a 0,618"}</div>{" "}<div className="fig-sub">{"Cociente Fₙ / Fₙ₊₁ de la sucesión. Pasa el cursor para ver cada término."}</div>{" "}<div className="chart-host" id="fig-fb-seq" />{" "}</div>{" "}<div className="rd-sentinel" data-l="fb-que" /></article>
      <article className="lesson" id="fb-trazar">{" "}<h3><span className="ln">{"6.2"}</span>{"Cómo se traza"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Impulso alcista:"}</strong>{" del "}<strong>{"mínimo"}</strong>{" del swing (100%) al "}<strong>{"máximo"}</strong>{" (0%). Los retrocesos quedan por debajo del máximo y miden cuánto \"devuelve\" el precio."}</li><li><strong>{"Impulso bajista:"}</strong>{" del "}<strong>{"máximo"}</strong>{" (100%) al "}<strong>{"mínimo"}</strong>{" (0%). Los retrocesos quedan por encima del mínimo."}</li><li>{"Usa "}<strong>{"swings claros"}</strong>{": el impulso debe romper estructura (un BOS). Trazar Fibonacci sobre un rango sin dirección da niveles sin sentido."}</li><li>{"Mechas o cuerpos: las dos convenciones existen. Lo importante es "}<strong>{"ser consistente"}</strong>{"."}</li><li>{"Retroceso por debajo del 50% = "}<strong>{"descuento"}</strong>{" (zona para comprar en tendencia alcista); por encima = "}<strong>{"premium"}</strong>{". Es el mismo concepto que viste en Liquidez."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="fb-trazar" /></article>
      <article className="lesson" id="fb-lab">{" "}<h3><span className="ln">{"6.3"}</span>{"Laboratorio: traza tu Fibonacci"}</h3>{" "}<div className="prose"><p><strong>{"Arrastra los dos puntos blancos"}</strong>{": el punto "}<b>{"1"}</b>{" va al inicio del impulso y el "}<b>{"0"}</b>{" a su final. Se imantan a las mechas cercanas. Con \"Ver el futuro\" se revela qué hizo el precio después y en qué nivel reaccionó."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="seg" data-key="dir"><button className="on" data-v="up">{"Impulso alcista"}</button><button data-v="down">{"Impulso bajista"}</button></div>{" "}<button className="btn primary" id="fb-auto">{"Trazado sugerido"}</button>{" "}<label className="grp"><input type="checkbox" id="fb-fut" />{" Ver el futuro"}</label>{" "}<label className="grp"><input type="checkbox" id="fb-ext-on" defaultChecked />{" Extensiones"}</label>{" "}<button className="btn" id="fb-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-fb" style={{"touchAction":"none"}} />{" "}<div className="readout" id="fb-stats" />{" "}<div className="explain" id="fb-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="fb-lab" /></article>
      <article className="lesson" id="fb-ext">{" "}<h3><span className="ln">{"6.4"}</span>{"Extensiones: dónde tomar ganancias"}</h3>{" "}<div className="prose">{" "}<p>{"Las extensiones proyectan el impulso "}<strong>{"más allá"}</strong>{" de su final. Con la misma herramienta, los niveles por encima del 0% (alcista) se leen como objetivos: "}<strong>{"−0,272"}</strong>{" (127,2%), "}<strong>{"−0,618"}</strong>{" (161,8%) y "}<strong>{"−1"}</strong>{" (el impulso repetido, \"AB = CD\")."}</p>{" "}<p>{"Úsalas para planificar "}<strong>{"salidas parciales"}</strong>{": el máximo anterior (liquidez) como primer objetivo y una extensión como segundo. Calcula el R:B "}<em>{"antes"}</em>{" de entrar: si desde tu entrada hasta el primer objetivo no hay al menos 2R, no hace falta Fibonacci para saber que la operación no vale la pena."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"Entrada en el retroceso"}</span><input type="range" id="fx-r" min="24" max="79" defaultValue="62" style={{"width":"200px"}} /><span className="val" id="fx-r-v" /></div>{" "}<div className="grp"><span className="lbl">{"Stop bajo el inicio (% del impulso)"}</span><input type="range" id="fx-s" min="0" max="20" defaultValue="5" style={{"width":"140px"}} /><span className="val" id="fx-s-v" /></div>{" "}</div>{" "}<div className="chart-host" id="fig-fb-ext" />{" "}<div id="fx-table" style={{"overflowX":"auto"}} />{" "}<div className="explain" id="fx-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="fb-ext" /></article>
      <article className="lesson" id="fb-conf">{" "}<h3><span className="ln">{"6.5"}</span>{"Confluencia: Fibonacci nunca va solo"}</h3>{" "}<div className="prose">{" "}<p>{"Un nivel de Fibonacci aislado es una línea más. Gana peso cuando "}<strong>{"coincide"}</strong>{" con otra cosa que el mercado también mira:"}</p>{" "}<ul><li>{"Un "}<strong>{"soporte/resistencia"}</strong>{" previo o un cambio de polaridad (módulo de soportes y resistencias)."}</li><li>{"Una "}<strong>{"EMA"}</strong>{" relevante (20 o 50) que pasa por la misma zona."}</li><li>{"Un "}<strong>{"FVG"}</strong>{" u "}<strong>{"order block"}</strong>{" dentro del 62–79%: es la "}<Link href="/smc/#smc-ote">{"OTE"}</Link>{" de ICT."}</li><li>{"Una "}<strong>{"línea de tendencia"}</strong>{" o el borde de un canal."}</li><li>{"Fibonacci de "}<strong>{"dos impulsos distintos"}</strong>{" que marcan el mismo precio (clúster)."}</li></ul>{" "}<p>{"Y en todos los casos, la confirmación llega del precio: una vela de rechazo, un CHoCH en temporalidad baja o un barrido de liquidez en la zona."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="fb-conf" /></article>
      <article className="lesson" id="fb-errores">{" "}<h3><span className="ln">{"6.6"}</span>{"Errores comunes"}</h3>{" "}<div className="callout err"><h5>{"Elegir el swing después de ver la reacción"}</h5>{"Si mueves los puntos hasta que algún nivel \"coincide\", siempre vas a encontrar uno: con 5–7 niveles, casi cualquier precio está cerca de alguno. Define el impulso "}<strong>{"antes"}</strong>{" de mirar."}</div>{" "}<div className="callout err"><h5>{"Entrar a ciegas en el 61,8%"}</h5>{"El nivel es una zona para buscar confirmación, no una orden límite automática. Muchas veces el precio lo atraviesa sin detenerse."}</div>{" "}<div className="callout err"><h5>{"Trazarlo en contra de la tendencia mayor"}</h5>{"Comprar en el 61,8% de un rebote dentro de una tendencia bajista de temporalidad alta es nadar contra la corriente."}</div>{" "}<div className="callout warn"><h5>{"Retroceso de más del 78,6%"}</h5>{"Si el precio devuelve casi todo el impulso, ese impulso perdió validez: la estructura que lo justificaba está en duda."}</div>{" "}<div className="rd-sentinel" data-l="fb-errores" /></article>
      <div id="fibo-quiz" />
    </>
  );
}
