// Contenido del módulo «Momentum y MACD». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Momentum() {
  return (
    <>
      <article className="lesson" id="mom-que">{" "}<h3><span className="ln">{"12.1"}</span>{"Qué es el momentum: posición, velocidad y aceleración"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Momentum (N)"}</strong>{" = cierre actual − cierre de hace N velas. Positivo: el precio está más alto que hace N velas."}</li><li><strong>{"ROC (N)"}</strong>{" (rate of change) = (cierre actual / cierre de hace N − 1) × 100: lo mismo en porcentaje, comparable entre activos."}</li><li>{"Analogía física: el precio es la "}<strong>{"posición"}</strong>{", el momentum la "}<strong>{"velocidad"}</strong>{" y su cambio la "}<strong>{"aceleración"}</strong>{". Una pelota lanzada hacia arriba frena antes de caer: la velocidad llega a cero en el punto más alto."}</li></ul>{" "}</div>{" "}<div className="fig">{" "}<div className="controls"><div className="grp"><span className="lbl">{"Mueve el tiempo"}</span><input type="range" id="mp-t" min="12" max="100" defaultValue="22" style={{"width":"300px"}} /></div></div>{" "}<div className="chart-host" id="fig-mom-phys" />{" "}<div className="explain" id="mp-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="mom-que" /></article>
      <article className="lesson" id="mom-lab">{" "}<h3><span className="ln">{"12.2"}</span>{"Laboratorio de momentum"}</h3>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Escenario"}</span>{" "}<div className="seg" data-key="sc"><button className="on" data-v="bear">{"Divergencia bajista"}</button><button data-v="bull">{"Divergencia alcista"}</button><button data-v="up">{"Tendencia"}</button><button data-v="range">{"Lateral"}</button></div>{" "}<span className="lbl">{"Indicador"}</span>{" "}<div className="seg" data-key="ind"><button className="on" data-v="macd">{"MACD"}</button><button data-v="mom">{"Momentum"}</button><button data-v="roc">{"ROC"}</button></div>{" "}<button className="btn" id="ml-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="controls" id="ml-params" />{" "}<div className="chart-host" id="fig-mom-lab" />{" "}<div className="legend" id="ml-legend" />{" "}<div className="readout" id="ml-stats" />{" "}<div className="explain" id="ml-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="mom-lab" /></article>
      <article className="lesson" id="mom-macd">{" "}<h3><span className="ln">{"12.3"}</span>{"MACD (Gerald Appel)"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Línea MACD"}</strong>{" = EMA 12 − EMA 26 del cierre. Mide si la media rápida se separa de la lenta (momentum de la tendencia)."}</li><li><strong>{"Línea de señal"}</strong>{" = EMA 9 de la línea MACD."}</li><li><strong>{"Histograma"}</strong>{" = MACD − señal: muestra si el momentum se acelera (barras crecientes) o se frena (barras que se encogen)."}</li><li>{"Señales habituales: cruce de MACD y señal, cruce de la línea cero (la EMA 12 cruza la 26), histograma que se encoge y divergencias."}</li></ul>{" "}<p>{"Como está hecho de medias móviles, el MACD hereda su retraso: es un indicador de "}<em>{"seguimiento de tendencia con información de momentum"}</em>{"."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="mom-macd" /></article>
      <article className="lesson" id="mom-uso">{" "}<h3><span className="ln">{"12.4"}</span>{"Momentum y tendencia: cómo combinarlos"}</h3>{" "}<div className="prose">{" "}<ul><li>{"El momentum "}<strong>{"se adelanta"}</strong>{": se frena antes de que el precio gire. Eso da avisos tempranos… y también falsos."}</li><li>{"Una pérdida de momentum dentro de una tendencia suele ser solo un "}<strong>{"retroceso"}</strong>{". Confirma con estructura (CHoCH), niveles y liquidez."}</li><li>{"La divergencia de momentum es más valiosa cuando el segundo extremo del precio "}<strong>{"barre liquidez"}</strong>{" (por ejemplo, un máximo anterior)."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="mom-uso" /></article>
      <div id="momentum-quiz" />
    </>
  );
}
