// Contenido del módulo «Patrones de velas». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Patrones() {
  return (
    <>
      <article className="lesson" id="pat-leer">{" "}<h3><span className="ln">{"2.1"}</span>{"Cómo leer un patrón (sin memorizar)"}</h3>{" "}<div className="prose">{" "}<ol><li><strong>{"Contexto:"}</strong>{" un patrón de giro alcista solo tiene sentido "}<em>{"después de una caída"}</em>{" (y uno bajista, después de una subida). Vale mucho más si aparece en un nivel relevante: soporte/resistencia, un barrido de liquidez, un order block o un FVG."}</li><li><strong>{"Tamaño:"}</strong>{" compáralo con las velas recientes. Un envolvente diminuto en mitad del ruido no significa nada."}</li><li><strong>{"Confirmación:"}</strong>{" casi todos los patrones necesitan que la vela siguiente vaya en la dirección esperada (por ejemplo, que cierre por encima del máximo del martillo)."}</li><li><strong>{"Invalidación:"}</strong>{" cada patrón tiene un nivel que lo anula (normalmente el extremo del patrón). Ahí va el stop."}</li></ol>{" "}<p>{"En lugar de memorizar nombres, lee la historia: "}<em>{"¿quién atacó, quién respondió y quién ganó al cierre?"}</em></p>{" "}</div>{" "}<div className="callout warn"><h5>{"Forex casi no tiene huecos (gaps)"}</h5>{"Muchas definiciones clásicas (estrella de la mañana, línea penetrante) piden huecos entre velas, típicos de acciones. En forex el mercado es continuo, así que se usan versiones flexibles: lo que importa es la forma de los cuerpos y dónde cierran."}</div>{" "}<div className="rd-sentinel" data-l="pat-leer" /></article>
      <article className="lesson" id="pat-explorador">{" "}<h3><span className="ln">{"2.2"}</span>{"Explorador de patrones"}</h3>{" "}<div className="prose"><p>{"Elige un patrón: verás su contexto (la tendencia previa), el patrón resaltado y las velas de confirmación, con sus reglas exactas."}</p></div>{" "}<div className="fig">{" "}<div className="controls" id="pat-list" />{" "}<div className="chart-host" id="fig-pat" />{" "}<div className="cols" style={{"marginTop":"10px"}}>{" "}<div className="explain" id="pat-info" />{" "}<div className="explain" id="pat-rules" />{" "}</div>{" "}</div>{" "}<div className="rd-sentinel" data-l="pat-explorador" /></article>
      <article className="lesson" id="pat-escaner">{" "}<h3><span className="ln">{"2.3"}</span>{"Escáner de patrones"}</h3>{" "}<div className="prose"><p>{"Un detector automático aplica las reglas a un gráfico simulado. Pasa el cursor por las marcas para ver el patrón, y revisa en la tabla qué pasó 5 velas después."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<label className="grp"><input type="checkbox" className="ps-f" defaultValue="bull" defaultChecked />{" Giros alcistas ▲"}</label>{" "}<label className="grp"><input type="checkbox" className="ps-f" defaultValue="bear" defaultChecked />{" Giros bajistas ▼"}</label>{" "}<label className="grp"><input type="checkbox" className="ps-f" defaultValue="neutral" />{" Indecisión ●"}</label>{" "}<label className="grp"><input type="checkbox" id="ps-ctx" />{" Solo en extremos de 20 velas (contexto)"}</label>{" "}<button className="btn" id="ps-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-pscan" />{" "}<div className="readout" id="ps-stats" />{" "}<div className="explain">{"Los datos de este gráfico son "}<strong>{"aleatorios"}</strong>{": ningún patrón tiene ventaja real aquí, y por eso los aciertos rondan el 50%. Sirve para entrenar el ojo, no para medir eficacia. Fuera del laboratorio, la ventaja (si existe) viene del "}<strong>{"contexto"}</strong>{": tendencia mayor, liquidez y niveles clave."}</div>{" "}<details className="data" id="ps-data"><summary>{"Ver patrones detectados"}</summary></details>{" "}</div>{" "}<div className="rd-sentinel" data-l="pat-escaner" /></article>
      <article className="lesson" id="pat-errores">{" "}<h3><span className="ln">{"2.4"}</span>{"Errores comunes"}</h3>{" "}<div className="callout err"><h5>{"Operar el patrón sin contexto"}</h5>{"Un martillo en mitad de un rango, lejos de cualquier nivel, es solo una vela con mecha."}</div>{" "}<div className="callout err"><h5>{"Confundir el nombre con la señal"}</h5>{"Martillo y hombre colgado tienen la misma forma: lo que cambia es la tendencia previa. Lo mismo con martillo invertido y estrella fugaz."}</div>{" "}<div className="callout err"><h5>{"Entrar antes de la confirmación"}</h5>{"La vela siguiente puede anular el patrón. Espera el cierre que lo confirma."}</div>{" "}<div className="rd-sentinel" data-l="pat-errores" /></article>
      <div id="patrones-quiz" />
    </>
  );
}
