// Contenido del módulo «Gestión del riesgo». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Riesgo() {
  return (
    <>
      <article className="lesson" id="rg-exp">{" "}<h3><span className="ln">{"19.1"}</span>{"Expectativa matemática"}</h3>{" "}<div className="prose">{" "}<p>{"Midiendo en "}<strong>{"R"}</strong>{" (1R = lo que arriesgas por operación):"}</p>{" "}<p style={{"fontFamily":"var(--mono)","color":"var(--strong)"}}>{"Expectativa = % de acierto × R:B − % de fallo × 1"}</p>{" "}<p>{"Ejemplo: aciertas el 40% con un R:B de 1:2 → 0,4 × 2 − 0,6 × 1 = "}<strong>{"+0,2R"}</strong>{" por operación. Se puede ganar acertando menos de la mitad… si las ganancias son más grandes que las pérdidas. Y se puede perder acertando el 70% si las pérdidas son enormes."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"% de acierto"}</span><input type="range" id="ex-wr" min="10" max="90" defaultValue="40" style={{"width":"160px"}} /><span className="val" id="ex-wr-v" /></div>{" "}<div className="grp"><span className="lbl">{"R:B (ganancia / riesgo)"}</span><input type="range" id="ex-rr" min="2" max="20" defaultValue="8" style={{"width":"160px"}} /><span className="val" id="ex-rr-v" /></div>{" "}</div>{" "}<div className="cols">{" "}<div className="chart-host" id="fig-ex" />{" "}<div>{" "}<div className="readout" id="ex-out" />{" "}<div className="explain" id="ex-explain" />{" "}<div className="legend"><span><i className="box" style={{"background":"#e66767"}} />{"Expectativa negativa"}</span><span><i className="box" style={{"background":"var(--heat-mid)"}} />{"≈ 0"}</span><span><i className="box" style={{"background":"#3987e5"}} />{"Expectativa positiva"}</span><span><i className="dash" style={{"borderColor":"var(--strong)"}} />{"Punto de equilibrio"}</span></div>{" "}</div>{" "}</div>{" "}</div>{" "}<div className="rd-sentinel" data-l="rg-exp" /></article>
      <article className="lesson" id="rg-mc">{" "}<h3><span className="ln">{"19.2"}</span>{"Simulador de rachas (Monte Carlo)"}</h3>{" "}<div className="prose"><p>{"Simula 1 000 cuentas que operan la misma estrategia con el orden de aciertos y fallos al azar. Mismo sistema, resultados muy distintos: así es la varianza. Compara arriesgar el 1% con arriesgar el 5% por operación."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"% de acierto"}</span><input type="range" id="mc-wr" min="20" max="80" defaultValue="45" style={{"width":"120px"}} /><span className="val" id="mc-wr-v" /></div>{" "}<div className="grp"><span className="lbl">{"R:B"}</span><input type="range" id="mc-rr" min="5" max="40" defaultValue="15" style={{"width":"110px"}} /><span className="val" id="mc-rr-v" /></div>{" "}<div className="grp"><span className="lbl">{"Riesgo por operación"}</span><input type="range" id="mc-risk" min="1" max="40" defaultValue="4" style={{"width":"120px"}} /><span className="val" id="mc-risk-v" /></div>{" "}<div className="grp"><span className="lbl">{"Operaciones"}</span><input type="range" id="mc-n" min="50" max="500" step="10" defaultValue="200" style={{"width":"120px"}} /><span className="val" id="mc-n-v" /></div>{" "}<button className="btn primary" id="mc-new">{"Nueva simulación"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-mc" />{" "}<div className="legend"><span><i style={{"background":"var(--text-2)"}} />{"40 cuentas de ejemplo"}</span><span><i style={{"background":"var(--strong)"}} />{"Mediana (cuenta típica)"}</span><span><i className="dash" style={{"borderColor":"var(--c-down)"}} />{"Peor 5%"}</span><span><i className="dash" style={{"borderColor":"var(--c-up)"}} />{"Mejor 5%"}</span></div>{" "}<div className="readout" id="mc-out" />{" "}<div className="explain" id="mc-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="rg-mc" /></article>
      <article className="lesson" id="rg-dd">{" "}<h3><span className="ln">{"19.3"}</span>{"Drawdown y recuperación: la asimetría que duele"}</h3>{" "}<div className="prose"><p>{"Si pierdes un X% de la cuenta, necesitas ganar "}<span className="mono">{"X / (100 − X)"}</span>{" para volver al punto de partida. Perder el 50% exige un +100%. Por eso proteger el capital pesa más que maximizar ganancias."}</p></div>{" "}<div className="fig">{" "}<div className="controls"><div className="grp"><span className="lbl">{"Pérdida"}</span><input type="range" id="dd-l" min="5" max="90" defaultValue="30" style={{"width":"220px"}} /><span className="val" id="dd-l-v" /></div></div>{" "}<div className="chart-host" id="fig-dd" />{" "}<div className="explain" id="dd-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="rg-dd" /></article>
      <article className="lesson" id="rg-rachas">{" "}<h3><span className="ln">{"19.4"}</span>{"Rachas perdedoras: más largas de lo que crees"}</h3>{" "}<div className="prose"><p>{"Racha perdedora más larga "}<strong>{"típica"}</strong>{" (mediana de 400 simulaciones) según tu % de acierto y el número de operaciones. Úsala para dimensionar el riesgo: tu cuenta debe aguantar estas rachas sin daño grave."}</p></div>{" "}<div className="fig"><div id="rg-table" style={{"overflowX":"auto"}} /><div className="explain" id="rg-tbl-explain" /></div>{" "}<div className="rd-sentinel" data-l="rg-rachas" /></article>
      <article className="lesson" id="rg-reglas">{" "}<h3><span className="ln">{"19.5"}</span>{"Reglas prácticas"}</h3>{" "}<div className="cols">{" "}<div className="callout tip-c"><h5>{"Haz"}</h5><ul style={{"marginLeft":"18px"}}><li>{"Arriesga una fracción "}<strong>{"fija y pequeña"}</strong>{" por operación (0,5–1% es lo habitual)."}</li><li>{"Define un "}<strong>{"límite de pérdida diario/semanal"}</strong>{" y respétalo."}</li><li>{"Reduce el tamaño durante los drawdowns; vuelve a subirlo al recuperar."}</li><li>{"Lleva un "}<strong>{"diario"}</strong>{" con cada operación (setup, R, emociones)."}</li><li>{"Valida la estrategia con "}<strong>{"backtest"}</strong>{" y en demo antes de usar dinero real."}</li></ul></div>{" "}<div className="callout err"><h5>{"Evita"}</h5><ul style={{"marginLeft":"18px"}}><li><strong>{"Martingala"}</strong>{" (doblar tras perder): acelera la ruina."}</li><li>{"Mover el stop \"para darle aire\" cuando el precio va en contra."}</li><li>{"Operar para \"recuperar\" tras una pérdida (revenge trading)."}</li><li>{"Juzgar una estrategia por 10 operaciones: la varianza manda en muestras pequeñas."}</li></ul></div>{" "}</div>{" "}<div className="rd-sentinel" data-l="rg-reglas" /></article>
      <div id="riesgo-quiz" />
    </>
  );
}
