// Contenido del módulo «Sesiones». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Sesiones() {
  return (
    <>
      <article className="lesson" id="ses-reloj">{" "}<h3><span className="ln">{"7.1"}</span>{"Reloj de sesiones en vivo"}</h3>{" "}<div className="prose"><p>{"Las barras muestran el horario de cada plaza (de 8 a 17 h aprox. en su hora local), convertido a la zona que elijas. El horario de verano de cada ciudad se calcula automáticamente para hoy. La línea vertical es "}<strong>{"ahora"}</strong>{"."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Mostrar en"}</span>{" "}<div className="seg" data-key="tz"><button className="on" data-v="local">{"Mi hora local"}</button><button data-v="America/New_York">{"Hora de Nueva York"}</button><button data-v="UTC">{"UTC"}</button></div>{" "}<label className="grp"><input type="checkbox" id="ses-kz-on" defaultChecked />{" Killzones ICT"}</label>{" "}</div>{" "}<div className="chart-host" id="fig-ses-clock" />{" "}<div className="explain" id="ses-now" />{" "}</div>{" "}<div className="rd-sentinel" data-l="ses-reloj" /></article>
      <article className="lesson" id="ses-tabla">{" "}<h3><span className="ln">{"7.2"}</span>{"Sesiones y solapamientos"}</h3>{" "}<div style={{"overflowX":"auto"}}>{" "}<table className="t wide"><thead><tr><th>{"Sesión"}</th><th>{"Horario local aprox."}</th><th>{"En hora de Nueva York (aprox.)"}</th><th>{"Carácter"}</th></tr></thead><tbody><tr><td><strong>{"Sídney"}</strong></td><td>{"07:00–16:00"}</td><td>{"~16:00/17:00 – 01:00/02:00"}</td><td>{"Abre la semana; volumen bajo."}</td></tr><tr><td><strong>{"Tokio (Asia)"}</strong></td><td>{"09:00–18:00"}</td><td>{"~19:00/20:00 – 04:00/05:00"}</td><td>{"Volumen moderado; suele formar rangos (JPY, AUD, NZD más activos)."}</td></tr><tr><td><strong>{"Londres"}</strong></td><td>{"08:00–17:00"}</td><td>{"~03:00 – 12:00"}</td><td>{"La sesión de mayor volumen del forex; suele romper o barrer el rango de Asia."}</td></tr><tr><td><strong>{"Nueva York"}</strong></td><td>{"08:00–17:00"}</td><td>{"08:00 – 17:00"}</td><td>{"Datos de EE. UU. y apertura de Wall Street (9:30); continúa o revierte el movimiento de Londres."}</td></tr></tbody></table>{" "}</div>{" "}<div className="prose">{" "}<ul><li><strong>{"Solapamiento Londres–Nueva York"}</strong>{" (~08:00–12:00 NY): el tramo más líquido y volátil del día."}</li><li><strong>{"Horario de verano:"}</strong>{" EE. UU., Reino Unido y Australia cambian la hora en fechas distintas (y Japón no la cambia), así que durante algunas semanas al año los horarios relativos se desplazan una hora. El reloj de arriba ya lo tiene en cuenta."}</li><li>{"El forex abre el domingo ~17:00 (NY) y cierra el viernes ~17:00 (NY)."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="ses-tabla" /></article>
      <article className="lesson" id="ses-dia">{" "}<h3><span className="ln">{"7.3"}</span>{"Un día típico: Asia acumula, Londres manipula, Nueva York expande"}</h3>{" "}<div className="prose"><p>{"Es un patrón "}<strong>{"frecuente"}</strong>{", no una regla: Asia forma un rango estrecho; Londres barre uno de sus extremos (el famoso \"Judas swing\") y luego gira; Nueva York continúa la expansión hacia la liquidez opuesta. Es la misma idea del Power of 3 (AMD) que verás en Smart Money y CRT."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="seg" data-key="day"><button className="on" data-v="bull">{"Día alcista"}</button><button data-v="bear">{"Día bajista"}</button></div>{" "}<button className="btn primary" id="ses-play">{"▶ Reproducir el día"}</button>{" "}<button className="btn" id="ses-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-ses-day" />{" "}<div className="explain" id="ses-day-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="ses-dia" /></article>
      <article className="lesson" id="ses-kz">{" "}<h3><span className="ln">{"7.4"}</span>{"Killzones (ICT)"}</h3>{" "}<div className="prose"><p>{"ICT llama "}<strong>{"killzones"}</strong>{" a las ventanas donde suelen aparecer los movimientos con intención (barridos, desplazamientos). Las horas varían según el autor; estas son las más citadas (hora de Nueva York):"}</p></div>{" "}<div style={{"overflowX":"auto"}}>{" "}<table className="t wide"><thead><tr><th>{"Killzone"}</th><th>{"Hora de Nueva York"}</th><th>{"Qué se busca"}</th></tr></thead><tbody><tr><td>{"Asia"}</td><td>{"20:00 – 00:00"}</td><td>{"Formación del rango de Asia (liquidez para más tarde)."}</td></tr><tr><td>{"Apertura de Londres"}</td><td>{"02:00 – 05:00"}</td><td>{"La ventana más consensuada: barrido del rango de Asia y primer movimiento del día."}</td></tr><tr><td>{"Apertura de Nueva York"}</td><td>{"07:00 – 10:00 (variantes 08:00/08:30 – 11:00)"}</td><td>{"Continuación o giro del movimiento de Londres; datos de las 8:30."}</td></tr><tr><td>{"Cierre de Londres"}</td><td>{"10:00 – 12:00"}</td><td>{"Toma de beneficios y retrocesos."}</td></tr></tbody></table>{" "}</div>{" "}<div className="rd-sentinel" data-l="ses-kz" /></article>
      <article className="lesson" id="ses-noticias">{" "}<h3><span className="ln">{"7.5"}</span>{"Noticias que mueven el mercado"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"EE. UU.:"}</strong>{" la mayoría de datos se publican a las "}<strong>{"8:30"}</strong>{" (NY): empleo (NFP, primer viernes de mes), inflación (CPI)… y otros a las 10:00. Las decisiones de la Fed (FOMC) salen a las "}<strong>{"14:00"}</strong>{" (NY)."}</li><li>{"En esos minutos el spread se amplía y aparecen mechas violentas: muchos traders evitan operar justo antes y después."}</li><li>{"Consulta siempre un calendario económico antes de la sesión."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="ses-noticias" /></article>
      <div id="sesiones-quiz" />
    </>
  );
}
