// Contenido del módulo «SMT». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Smt() {
  return (
    <>
      <article className="lesson" id="smt-que">{" "}<h3><span className="ln">{"17.1"}</span>{"Cómo se ve una divergencia SMT"}</h3>{" "}<div className="prose">{" "}<p>{"A diferencia de la divergencia del RSI (precio contra indicador), la SMT compara "}<strong>{"precio contra precio"}</strong>{" de otro activo. Ejemplo alcista con EUR/USD y GBP/USD: ambos bajan juntos, pero en el último mínimo el EUR/USD hace un "}<strong>{"mínimo más bajo"}</strong>{" (barre la liquidez) mientras el GBP/USD hace un "}<strong>{"mínimo más alto"}</strong>{". La caída del euro no fue confirmada: señal de fuerza oculta."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="seg" data-key="t"><button className="on" data-v="bull">{"SMT alcista (en mínimos)"}</button><button data-v="bear">{"SMT bajista (en máximos)"}</button></div>{" "}<div className="seg" data-key="rel"><button className="on" data-v="pos">{"EUR/USD vs GBP/USD"}</button><button data-v="inv">{"EUR/USD vs DXY (inversa)"}</button></div>{" "}<button className="btn primary" id="smt-play">{"▶ Reproducir"}</button>{" "}<button className="btn" id="smt-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-smt" />{" "}<div className="legend"><span><i style={{"background":"var(--c-div)"}} />{"Divergencia SMT (une los dos extremos de cada activo)"}</span><span><i className="dash" style={{"borderColor":"var(--c-liq)"}} />{"Liquidez del extremo anterior"}</span><span><i className="dash" style={{"borderColor":"var(--muted)"}} />{"Mismo momento en ambos gráficos"}</span></div>{" "}<div className="explain" id="smt-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="smt-que" /></article>
      <article className="lesson" id="smt-tipos">{" "}<h3><span className="ln">{"17.2"}</span>{"Tipos y pares habituales"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"SMT alcista"}</strong>{" (en mínimos): A hace un mínimo más bajo, B un mínimo más alto."}</li><li><strong>{"SMT bajista"}</strong>{" (en máximos): A hace un máximo más alto, B un máximo más bajo."}</li><li><strong>{"Correlación inversa"}</strong>{" (p. ej. EUR/USD contra el índice del dólar DXY): se compara el mínimo de uno con el máximo del otro. SMT alcista en EUR/USD: el euro hace un mínimo más bajo, pero el DXY "}<em>{"no"}</em>{" hace un máximo más alto."}</li></ul>{" "}</div>{" "}<div style={{"overflowX":"auto"}}>{" "}<table className="t wide"><thead><tr><th>{"Grupo"}</th><th>{"Activos"}</th><th>{"Correlación"}</th></tr></thead><tbody><tr><td>{"Forex (frente al dólar)"}</td><td>{"EUR/USD – GBP/USD (también AUD/USD – NZD/USD)"}</td><td>{"Positiva"}</td></tr><tr><td>{"Forex frente al índice dólar"}</td><td>{"EUR/USD – DXY (el euro pesa mucho en el DXY)"}</td><td>{"Inversa"}</td></tr><tr><td>{"Índices de EE. UU."}</td><td>{"ES (S&P 500) – NQ (Nasdaq 100) – YM (Dow Jones)"}</td><td>{"Positiva"}</td></tr><tr><td>{"Metales"}</td><td>{"Oro (XAU/USD) – Plata (XAG/USD)"}</td><td>{"Positiva"}</td></tr><tr><td>{"Cripto"}</td><td>{"BTC – ETH"}</td><td>{"Positiva"}</td></tr></tbody></table>{" "}</div>{" "}<div className="rd-sentinel" data-l="smt-tipos" /></article>
      <article className="lesson" id="smt-reglas">{" "}<h3><span className="ln">{"17.3"}</span>{"Reglas de uso"}</h3>{" "}<div className="prose">{" "}<ol><li><strong>{"Mismo momento y misma temporalidad:"}</strong>{" compara los extremos que se formaron en las mismas velas (los activos correlacionados pueden girar con unos minutos de diferencia)."}</li><li><strong>{"En un nivel relevante:"}</strong>{" barrido de PDH/PDL, extremo de sesión, CRT High/Low o zona de temporalidad mayor. Una \"SMT\" en mitad del rango vale poco."}</li><li><strong>{"Confirmación:"}</strong>{" después de la SMT, espera un MSS o CISD en temporalidad baja antes de entrar."}</li><li><strong>{"Cuidado con las noticias de un solo activo:"}</strong>{" un dato del Reino Unido mueve la libra y no el euro; eso rompe la correlación por motivos fundamentales, no por \"dinero inteligente\"."}</li><li><strong>{"Comprueba que la correlación siga vigente:"}</strong>{" las correlaciones cambian con el tiempo."}</li></ol>{" "}<h4>{"¿Qué activo operar?"}</h4>{" "}<p>{"Hay dos enfoques: operar el activo que "}<strong>{"barrió la liquidez"}</strong>{" (tiene un barrido claro y un stop lógico detrás) o el activo "}<strong>{"\"fuerte\""}</strong>{" que no hizo el nuevo extremo (mostró más fuerza relativa). Elige un criterio y sé consistente."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="smt-reglas" /></article>
      <article className="lesson" id="smt-crt">{" "}<h3><span className="ln">{"17.4"}</span>{"SMT + CRT: la combinación más usada"}</h3>{" "}<div className="prose"><p>{"Aplica la CRT a los dos activos a la vez. Si la vela 2 del EUR/USD barre su CRT Low pero la vela 2 del GBP/USD "}<strong>{"no"}</strong>{" barre el suyo, tienes un CRT alcista confirmado por una SMT alcista: dos señales independientes que cuentan lo mismo."}</p></div>{" "}<div className="fig">{" "}<div className="controls"><div className="seg" data-key="sc"><button className="on" data-v="bull">{"Alcista"}</button><button data-v="bear">{"Bajista"}</button></div></div>{" "}<div className="chart-host" id="fig-smt-crt" />{" "}<div className="explain" id="smt-crt-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="smt-crt" /></article>
      <article className="lesson" id="smt-errores">{" "}<h3><span className="ln">{"17.5"}</span>{"Errores comunes"}</h3>{" "}<div className="callout err"><h5>{"Buscar SMT en temporalidades muy bajas sin contexto"}</h5>{"En 1 minuto siempre aparece alguna \"divergencia\". Úsala en niveles relevantes."}</div>{" "}<div className="callout err"><h5>{"Comparar extremos de momentos distintos"}</h5>{"Un mínimo del lunes en un activo contra uno del martes en el otro no es una SMT."}</div>{" "}<div className="callout err"><h5>{"Entrar solo por la SMT"}</h5>{"Es una confirmación, no un gatillo: espera estructura (MSS / CISD) y define stop y objetivo."}</div>{" "}<div className="rd-sentinel" data-l="smt-errores" /></article>
      <div id="smt-quiz" />
    </>
  );
}
