// Contenido del módulo «Todo junto». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Todo() {
  return (
    <>
      <article className="lesson" id="todo-sim">{" "}<h3><span className="ln">{"20.1"}</span>{"Simulación guiada: CRT alcista en EUR/USD con SMT y RSI"}</h3>{" "}<div className="fig">{" "}<div className="steps-nav"><button className="btn" id="todo-prev">{"◀ Anterior"}</button><div className="dots" id="todo-dots" /><button className="btn primary" id="todo-next">{"Siguiente ▶"}</button><button className="btn" id="todo-new">{"Nuevo escenario"}</button></div>{" "}<div className="step-box" id="todo-step" />{" "}<div className="chart-host" id="fig-todo" />{" "}<div className="legend"><span><i className="dash" style={{"borderColor":"var(--c-range)"}} />{"Rango CRT"}</span><span><i className="dash" style={{"borderColor":"var(--c-liq)"}} />{"Liquidez"}</span><span><i style={{"background":"var(--c-div)"}} />{"Divergencias (SMT / RSI)"}</span><span><i className="box" style={{"background":"var(--c-fvg)"}} />{"FVG"}</span><span><i style={{"background":"var(--c-rsi)"}} />{"RSI 14"}</span><span><i className="box" style={{"background":"var(--c-down)"}} />{"Riesgo"}</span><span><i className="box" style={{"background":"var(--c-up)"}} />{"Beneficio"}</span></div>{" "}<div className="readout" id="todo-stats" />{" "}</div>{" "}<div className="rd-sentinel" data-l="todo-sim" /></article>
      <article className="lesson" id="todo-check">{" "}<h3><span className="ln">{"20.2"}</span>{"Checklist antes de entrar"}</h3>{" "}<div className="prose"><p>{"Marca lo que cumple tu operación. No es una probabilidad: es una herramienta de "}<strong>{"disciplina"}</strong>{" para no operar por impulso. Si faltan los puntos obligatorios (★), no hay operación."}</p></div>{" "}<div className="checklist" id="checklist" />{" "}<div className="meter"><div id="check-meter" /></div>{" "}<div className="explain" id="check-explain" />{" "}<div className="rd-sentinel" data-l="todo-check" /></article>
      <article className="lesson" id="todo-riesgo">{" "}<h3><span className="ln">{"20.3"}</span>{"Gestión del riesgo: tamaño de posición"}</h3>{" "}<div className="prose"><p>{"Ningún modelo acierta siempre. Lo que te mantiene en el juego es arriesgar una fracción pequeña y fija de la cuenta por operación (muchos usan 0,5–1%) y exigir un riesgo/beneficio razonable."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"Capital ($)"}</span><input type="number" id="rk-cap" defaultValue="10000" min="0" style={{"width":"110px"}} /></div>{" "}<div className="grp"><span className="lbl">{"Riesgo por operación (%)"}</span><input type="number" id="rk-pct" defaultValue="1" min="0" step="0.1" style={{"width":"80px"}} /></div>{" "}<div className="grp"><span className="lbl">{"Entrada"}</span><input type="number" id="rk-entry" defaultValue="1.08250" step="0.0001" style={{"width":"110px"}} /></div>{" "}<div className="grp"><span className="lbl">{"Stop"}</span><input type="number" id="rk-stop" defaultValue="1.08050" step="0.0001" style={{"width":"110px"}} /></div>{" "}<div className="grp"><span className="lbl">{"Objetivo"}</span><input type="number" id="rk-tp" defaultValue="1.08650" step="0.0001" style={{"width":"110px"}} /></div>{" "}</div>{" "}<div className="readout" id="rk-out" />{" "}<div className="explain" id="rk-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="todo-riesgo" /></article>
    </>
  );
}
