// Contenido del módulo «Líneas de tendencia». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Trendlines() {
  return (
    <>
      <article className="lesson" id="tl-trazar">{" "}<h3><span className="ln">{"5.1"}</span>{"Cómo trazar una línea de tendencia"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Alcista:"}</strong>{" une al menos dos "}<strong>{"mínimos crecientes"}</strong>{"; la línea queda por debajo del precio. "}<strong>{"Bajista:"}</strong>{" une "}<strong>{"máximos decrecientes"}</strong>{"; queda por encima."}</li><li>{"Dos puntos la "}<em>{"definen"}</em>{"; el "}<strong>{"tercer toque la valida"}</strong>{"."}</li><li>{"Puedes usar mechas o cuerpos, pero "}<strong>{"sé consistente"}</strong>{", y no la \"fuerces\" cortando velas por la mitad."}</li><li>{"Cuantos más toques y más larga sea, más relevante (y más stops acumula debajo/encima)."}</li><li>{"La "}<strong>{"pendiente"}</strong>{" importa: una línea muy empinada describe un ritmo difícil de sostener y suele romperse antes."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="tl-trazar" /></article>
      <article className="lesson" id="tl-dibuja">{" "}<h3><span className="ln">{"5.2"}</span>{"Dibuja tu línea"}</h3>{" "}<div className="prose"><p><strong>{"Arrastra los dos puntos blancos"}</strong>{" hasta los mínimos (o máximos) que quieras unir: se \"imantan\" a las mechas cercanas. La página cuenta los toques y detecta la ruptura y el retesteo. Usa \"Línea sugerida\" para ver la que propone el algoritmo."}</p></div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="seg" data-key="sc"><button className="on" data-v="up">{"Tendencia alcista"}</button><button data-v="down">{"Tendencia bajista"}</button></div>{" "}<button className="btn primary" id="tl-auto">{"Línea sugerida"}</button>{" "}<label className="grp"><input type="checkbox" id="tl-ch" />{" Canal paralelo"}</label>{" "}<label className="grp"><input type="checkbox" id="tl-liq" />{" Liquidez (stops)"}</label>{" "}<button className="btn" id="tl-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-tl" style={{"touchAction":"none"}} />{" "}<div className="readout" id="tl-stats" />{" "}<div className="explain" id="tl-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="tl-dibuja" /></article>
      <article className="lesson" id="tl-ruptura">{" "}<h3><span className="ln">{"5.3"}</span>{"Ruptura, retesteo y canal"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Ruptura:"}</strong>{" un cierre claro al otro lado de la línea. Indica que el ritmo de la tendencia cambió, "}<em>{"no"}</em>{" necesariamente que la tendencia terminó: la confirmación llega con la estructura (CHoCH)."}</li><li><strong>{"Retesteo:"}</strong>{" tras romper, el precio suele volver a la línea desde el otro lado. Si la rechaza, el antiguo soporte se convirtió en resistencia (o al revés)."}</li><li><strong>{"Canal:"}</strong>{" una paralela por el extremo opuesto. Sirve para ver objetivos y cuándo el precio está \"estirado\" dentro de la tendencia. Actívalo arriba con \"Canal paralelo\"."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="tl-ruptura" /></article>
      <article className="lesson" id="tl-liquidez">{" "}<h3><span className="ln">{"5.4"}</span>{"Líneas de tendencia como liquidez"}</h3>{" "}<div className="prose">{" "}<p>{"Cada vez que el precio toca la línea, muchos compran ahí y ponen el stop justo debajo. Después de 3 o 4 toques hay una \"escalera\" de stops bajo la línea: "}<strong>{"liquidez de línea de tendencia"}</strong>{" (concepto muy usado en ICT). Por eso es frecuente ver que el precio rompe la línea con fuerza, activa esos stops… y a veces gira después, ya con la liquidez tomada. Activa \"Liquidez (stops)\" en el laboratorio para verla."}</p>{" "}<p>{"Moraleja: una línea con muchos toques es a la vez "}<strong>{"soporte"}</strong>{" y "}<strong>{"objetivo de liquidez"}</strong>{". No pongas tu stop donde lo pone todo el mundo."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="tl-liquidez" /></article>
      <article className="lesson" id="tl-errores">{" "}<h3><span className="ln">{"5.5"}</span>{"Errores comunes"}</h3>{" "}<div className="callout err"><h5>{"Forzar la línea"}</h5>{"Si tienes que atravesar velas para que \"encaje\", no es una línea válida."}</div>{" "}<div className="callout err"><h5>{"Operar cada ruptura"}</h5>{"Muchas rupturas de línea son solo barridos o cambios de ritmo. Espera estructura (cierre y CHoCH) o el retesteo."}</div>{" "}<div className="callout err"><h5>{"Usar la escala equivocada"}</h5>{"La inclinación visual cambia con la escala del gráfico: no te guíes por \"grados\", sino por los toques y la estructura."}</div>{" "}<div className="rd-sentinel" data-l="tl-errores" /></article>
      <div id="trendlines-quiz" />
    </>
  );
}
