// Contenido del módulo «Velas». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Velas() {
  return (
    <>
      <article className="lesson" id="velas-anatomia">{" "}<h3><span className="ln">{"1.1"}</span>{"Anatomía: OHLC, cuerpo y mechas"}</h3>{" "}<div className="prose">{" "}<p>{"Cada vela tiene cuatro precios, conocidos como "}<strong>{"OHLC"}</strong>{": "}<strong>{"Apertura"}</strong>{" (Open), "}<strong>{"Máximo"}</strong>{" (High), "}<strong>{"Mínimo"}</strong>{" (Low) y "}<strong>{"Cierre"}</strong>{" (Close)."}</p>{" "}<ul><li><strong>{"Cuerpo:"}</strong>{" el tramo entre la apertura y el cierre. Si el cierre queda por encima de la apertura, la vela es "}<strong>{"alcista"}</strong>{"; si queda por debajo, es "}<strong>{"bajista"}</strong>{"."}</li><li><strong>{"Mecha superior"}</strong>{" (o sombra): del cuerpo hasta el máximo. El precio llegó ahí, pero no se sostuvo."}</li><li><strong>{"Mecha inferior"}</strong>{": del cuerpo hasta el mínimo."}</li><li><strong>{"Rango"}</strong>{" = máximo − mínimo: todo el territorio que recorrió el precio en ese periodo."}</li></ul>{" "}</div>{" "}<div className="fig">{" "}<div className="fig-title">{"Las dos velas básicas"}</div>{" "}<div className="fig-sub">{"Pasa el cursor por cada parte para ver qué significa."}</div>{" "}<div className="chart-host" id="fig-anatomy" />{" "}<div className="explain" id="anatomy-explain">{"La "}<strong>{"mecha"}</strong>{" muestra dónde estuvo el precio y fue rechazado; el "}<strong>{"cuerpo"}</strong>{" muestra dónde terminó aceptándose. El "}<strong>{"cierre"}</strong>{" es el dato más importante: dice quién ganó la \"batalla\" del periodo."}</div>{" "}</div>{" "}<div className="rd-sentinel" data-l="velas-anatomia" /></article>
      <article className="lesson" id="velas-constructor">{" "}<h3><span className="ln">{"1.2"}</span>{"Constructor de velas"}</h3>{" "}<div className="prose">{" "}<p>{"Mueve los cuatro precios y observa cómo cambia la vela y lo que \"cuenta\". El máximo nunca puede quedar por debajo del cuerpo ni el mínimo por encima: el constructor lo ajusta solo."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls" id="builder-controls">{" "}<div className="grp"><span className="lbl">{"Apertura"}</span><input type="range" id="b-o" min="0" max="100" defaultValue="40" /><span className="val" id="b-o-v" /></div>{" "}<div className="grp"><span className="lbl">{"Máximo"}</span><input type="range" id="b-h" min="0" max="100" defaultValue="80" /><span className="val" id="b-h-v" /></div>{" "}<div className="grp"><span className="lbl">{"Mínimo"}</span><input type="range" id="b-l" min="0" max="100" defaultValue="20" /><span className="val" id="b-l-v" /></div>{" "}<div className="grp"><span className="lbl">{"Cierre"}</span><input type="range" id="b-c" min="0" max="100" defaultValue="70" /><span className="val" id="b-c-v" /></div>{" "}</div>{" "}<div className="controls">{" "}<span className="lbl">{"Ejemplos:"}</span>{" "}<button className="btn" data-preset="marubozu">{"Marubozu"}</button>{" "}<button className="btn" data-preset="doji">{"Doji"}</button>{" "}<button className="btn" data-preset="hammer">{"Martillo / pin bar alcista"}</button>{" "}<button className="btn" data-preset="star">{"Estrella fugaz"}</button>{" "}<button className="btn" data-preset="spin">{"Peonza"}</button>{" "}<button className="btn" data-preset="bear">{"Bajista de impulso"}</button>{" "}</div>{" "}<div className="cols">{" "}<div className="chart-host" id="fig-builder" />{" "}<div>{" "}<div className="readout" id="builder-stats" />{" "}<div className="explain" id="builder-explain" />{" "}</div>{" "}</div>{" "}</div>{" "}<div className="callout warn"><h5>{"El contexto manda"}</h5>{"La misma forma significa cosas distintas según dónde aparezca. Un \"martillo\" en mitad de la nada no dice mucho; uno que barre un mínimo importante y cierra de vuelta dentro, sí. Esa idea es la base de la liquidez y de la CRT."}</div>{" "}<div className="rd-sentinel" data-l="velas-constructor" /></article>
      <article className="lesson" id="velas-formacion">{" "}<h3><span className="ln">{"1.3"}</span>{"Cómo se forma una vela, tick a tick"}</h3>{" "}<div className="prose">{" "}<p>{"Una vela no \"aparece\": se va dibujando mientras el precio se mueve. La apertura queda fija, el cuerpo sigue al precio y las mechas quedan como "}<strong>{"huella"}</strong>{" de los extremos que se visitaron. Reproduce la animación: a la izquierda ves el recorrido del precio; a la derecha, la vela que resulta."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="seg" data-key="form"><button className="on" data-v="rechazo-abajo">{"Rechazo abajo"}</button><button data-v="rechazo-arriba">{"Rechazo arriba"}</button><button data-v="tendencia">{"Tendencia"}</button><button data-v="indecision">{"Indecisión"}</button></div>{" "}<button className="btn primary" id="form-play">{"▶ Reproducir"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-form" />{" "}<div className="explain" id="form-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="velas-formacion" /></article>
      <article className="lesson" id="velas-tf">{" "}<h3><span className="ln">{"1.4"}</span>{"Temporalidades: una vela grande contiene muchas pequeñas"}</h3>{" "}<div className="prose">{" "}<p>{"Los mismos datos se pueden agrupar en velas de 1 hora, 4 horas o 1 día. Una vela de 4H tiene la "}<strong>{"apertura"}</strong>{" de su primera vela de 1H, el "}<strong>{"cierre"}</strong>{" de la última, y el "}<strong>{"máximo/mínimo"}</strong>{" de todas ellas. Esto es clave para la CRT: "}<em>{"cada vela de temporalidad alta es un rango"}</em>{" que se \"construye\" con velas pequeñas."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Agrupar en:"}</span>{" "}<div className="seg" data-key="tf"><button className="on" data-v="1">{"1H"}</button><button data-v="4">{"4H"}</button><button data-v="24">{"1D"}</button></div>{" "}<button className="btn" id="tf-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-tf" />{" "}<div className="explain">{"Pasa el cursor sobre una vela de 4H o 1D: las bandas sombreadas marcan qué velas de 1H la forman. Observa que una mecha larga en 4H suele ser, en 1H, un movimiento completo de ida y vuelta."}</div>{" "}<details className="data" id="tf-data"><summary>{"Ver tabla de datos"}</summary></details>{" "}</div>{" "}<div className="rd-sentinel" data-l="velas-tf" /></article>
      <article className="lesson" id="velas-galeria">{" "}<h3><span className="ln">{"1.5"}</span>{"Formas comunes (y qué cuentan)"}</h3>{" "}<div className="prose"><p>{"No hace falta memorizar decenas de patrones. Estas formas describen la \"batalla\" dentro de la vela; su valor real depende de "}<strong>{"dónde"}</strong>{" aparecen."}</p></div>{" "}<div className="gallery" id="gallery" />{" "}<div className="rd-sentinel" data-l="velas-galeria" /></article>
      <div id="velas-quiz" />
    </>
  );
}
