// Contenido del módulo «ATR y Bollinger». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Volat() {
  return (
    <>
      <article className="lesson" id="vo-tr">{" "}<h3><span className="ln">{"13.1"}</span>{"True Range: el rango \"verdadero\" de una vela"}</h3>{" "}<div className="prose">{" "}<p>{"J. Welles Wilder (el mismo autor del RSI, 1978) definió el "}<strong>{"True Range"}</strong>{" para no ignorar los huecos entre velas:"}</p>{" "}<p style={{"fontFamily":"var(--mono)","color":"var(--strong)"}}>{"TR = el mayor de: (Máximo − Mínimo), |Máximo − Cierre anterior|, |Mínimo − Cierre anterior|"}</p>{" "}<p>{"El "}<strong>{"ATR"}</strong>{" (Average True Range) es la media del TR con el suavizado de Wilder, normalmente de 14 periodos. Se mide en unidades de precio (pips, puntos, dólares)."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"Cierre anterior"}</span><input type="range" id="tr-pc" min="0" max="100" defaultValue="45" style={{"width":"140px"}} /></div>{" "}<div className="grp"><span className="lbl">{"Máximo actual"}</span><input type="range" id="tr-h" min="0" max="100" defaultValue="80" style={{"width":"140px"}} /></div>{" "}<div className="grp"><span className="lbl">{"Mínimo actual"}</span><input type="range" id="tr-l" min="0" max="100" defaultValue="55" style={{"width":"140px"}} /></div>{" "}</div>{" "}<div className="chart-host" id="fig-tr" />{" "}<div className="explain" id="tr-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="vo-tr" /></article>
      <article className="lesson" id="vo-atr">{" "}<h3><span className="ln">{"13.2"}</span>{"Laboratorio de ATR"}</h3>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Escenario"}</span>{" "}<div className="seg" data-key="sc"><button className="on" data-v="squeeze">{"Calma → expansión"}</button><button data-v="trend">{"Tendencia"}</button><button data-v="news">{"Noticia"}</button></div>{" "}<div className="grp"><span className="lbl">{"Periodo"}</span><input type="range" id="atr-n" min="5" max="30" defaultValue="14" style={{"width":"110px"}} /><span className="val" id="atr-n-v">{"14"}</span></div>{" "}<button className="btn" id="atr-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-atr" />{" "}<div className="legend"><span><i className="box" style={{"background":"var(--text-2)"}} />{"True Range de cada vela"}</span><span><i style={{"background":"var(--c-range)"}} />{"ATR"}</span></div>{" "}<div className="explain" id="atr-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="vo-atr" /></article>
      <article className="lesson" id="vo-stops">{" "}<h3><span className="ln">{"13.3"}</span>{"Stops y tamaño de posición con ATR"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Stop por volatilidad:"}</strong>{" en lugar de un número fijo, el stop se pone a k × ATR de la entrada (k entre 1,5 y 3 es habitual). En un mercado nervioso el stop se aleja; en uno tranquilo, se acerca."}</li><li><strong>{"Tamaño:"}</strong>{" unidades = dinero arriesgado / (k × ATR). Así cada operación arriesga lo mismo aunque la volatilidad cambie."}</li><li><strong>{"Chandelier exit"}</strong>{" (stop dinámico de Chuck LeBeau): máximo más alto desde la entrada − m × ATR (m ≈ 3). Acompaña la tendencia y te saca cuando el retroceso supera lo \"normal\"."}</li></ul>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<div className="grp"><span className="lbl">{"Vela de entrada"}</span><input type="range" id="as-e" min="2" max="40" defaultValue="6" style={{"width":"120px"}} /><span className="val" id="as-e-v" /></div>{" "}<div className="grp"><span className="lbl">{"Stop inicial (k × ATR)"}</span><input type="range" id="as-k" min="10" max="40" defaultValue="20" style={{"width":"110px"}} /><span className="val" id="as-k-v" /></div>{" "}<div className="grp"><span className="lbl">{"Chandelier (m × ATR)"}</span><input type="range" id="as-m" min="10" max="50" defaultValue="30" style={{"width":"110px"}} /><span className="val" id="as-m-v" /></div>{" "}<div className="grp"><span className="lbl">{"Riesgo ($)"}</span><input type="number" id="as-r" defaultValue="100" min="1" style={{"width":"90px"}} /></div>{" "}</div>{" "}<div className="chart-host" id="fig-atr-stop" />{" "}<div className="readout" id="as-stats" />{" "}<div className="explain" id="as-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="vo-stops" /></article>
      <article className="lesson" id="vo-bb">{" "}<h3><span className="ln">{"13.4"}</span>{"Bandas de Bollinger"}</h3>{" "}<div className="prose">{" "}<p>{"Creadas por John Bollinger en los años 80: una media simple de 20 periodos (banda media) y dos bandas a ±2 desviaciones estándar. Se ensanchan cuando sube la volatilidad y se estrechan cuando baja. Dos lecturas derivadas: "}<strong>{"%B"}</strong>{" (dónde está el cierre respecto a las bandas: 1 = en la superior, 0 = en la inferior) y el "}<strong>{"ancho de banda"}</strong>{" ((superior − inferior) / media)."}</p>{" "}</div>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Escenario"}</span>{" "}<div className="seg" data-key="sc"><button className="on" data-v="squeeze">{"Squeeze → ruptura"}</button><button data-v="trend">{"Tendencia"}</button><button data-v="range">{"Rango"}</button></div>{" "}<div className="grp"><span className="lbl">{"Periodo"}</span><input type="range" id="bb-n" min="10" max="50" defaultValue="20" style={{"width":"100px"}} /><span className="val" id="bb-n-v">{"20"}</span></div>{" "}<div className="grp"><span className="lbl">{"Desviaciones"}</span><input type="range" id="bb-k" min="10" max="30" defaultValue="20" style={{"width":"90px"}} /><span className="val" id="bb-k-v">{"2.0"}</span></div>{" "}<label className="grp"><input type="checkbox" id="bb-pb" defaultChecked />{" %B"}</label>{" "}<label className="grp"><input type="checkbox" id="bb-bw" defaultChecked />{" Ancho de banda"}</label>{" "}</div>{" "}<div className="chart-host" id="fig-bb" />{" "}<div className="legend"><span><i style={{"background":"var(--c-range)"}} />{"Bandas superior e inferior"}</span><span><i className="dash" style={{"borderColor":"var(--text-2)"}} />{"Media (banda central)"}</span><span>{"● Cierre fuera de las bandas"}</span></div>{" "}<div className="readout" id="bb-stats" />{" "}<div className="explain" id="bb-explain" />{" "}</div>{" "}<div className="rd-sentinel" data-l="vo-bb" /></article>
      <article className="lesson" id="vo-uso">{" "}<h3><span className="ln">{"13.5"}</span>{"Cómo usarlas (y errores comunes)"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Squeeze:"}</strong>{" bandas muy estrechas (ancho de banda mínimo) = volatilidad comprimida. Suele preceder a una expansión, pero "}<em>{"no dice la dirección"}</em>{": espera la ruptura."}</li><li><strong>{"Tendencia:"}</strong>{" el precio puede \"caminar\" por la banda superior durante muchas velas. Cerrar fuera de la banda no es, por sí solo, señal de giro."}</li><li><strong>{"Rango:"}</strong>{" los toques de las bandas tienden a volver hacia la media: es donde funciona la lectura de \"reversión\"."}</li><li><strong>{"ATR:"}</strong>{" úsalo para dimensionar, no para predecir. Un ATR alto exige stops más amplios y posiciones más pequeñas."}</li></ul>{" "}</div>{" "}<div className="callout err"><h5>{"Error típico"}</h5>{"Vender cada toque de la banda superior en una tendencia alcista. Primero identifica si estás en tendencia o en rango (estructura de mercado)."}</div>{" "}<div className="rd-sentinel" data-l="vo-uso" /></article>
      <div id="volat-quiz" />
    </>
  );
}
