// Contenido del módulo «Volumen». Generado por scripts/port-legacy.mjs a partir de legacy/index.html.
// @ts-nocheck

export default function Volumen() {
  return (
    <>
      <article className="lesson" id="vol-que">{" "}<h3><span className="ln">{"8.1"}</span>{"Qué es el volumen"}</h3>{" "}<div className="prose">{" "}<p>{"Es la cantidad negociada en cada vela: acciones, contratos o lotes. Se dibuja como barras debajo del gráfico."}</p>{" "}<p><strong>{"En forex spot no hay un volumen centralizado"}</strong>{" (no existe una única bolsa). Las plataformas muestran el "}<strong>{"volumen de ticks"}</strong>{": cuántas veces cambió el precio en la vela. Es una aproximación de la actividad que suele moverse en línea con el volumen real. Para volumen real de divisas se usan los futuros (por ejemplo, el futuro del euro en el CME)."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="vol-que" /></article>
      <article className="lesson" id="vol-lab">{" "}<h3><span className="ln">{"8.2"}</span>{"Laboratorio de volumen"}</h3>{" "}<div className="fig">{" "}<div className="controls">{" "}<span className="lbl">{"Escenario"}</span>{" "}<div className="seg" data-key="sc"><button className="on" data-v="breakout">{"Ruptura con volumen"}</button><button data-v="fake">{"Ruptura sin volumen"}</button><button data-v="climax">{"Clímax de venta"}</button><button data-v="div">{"Subida sin volumen"}</button></div>{" "}</div>{" "}<div className="controls">{" "}<label className="grp"><input type="checkbox" className="vl" defaultValue="ma" defaultChecked />{" Media de volumen (20)"}</label>{" "}<label className="grp"><input type="checkbox" className="vl" defaultValue="obv" />{" OBV"}</label>{" "}<label className="grp"><input type="checkbox" className="vl" defaultValue="vwap" />{" VWAP (+ bandas)"}</label>{" "}<label className="grp"><input type="checkbox" className="vl" defaultValue="vp" />{" Perfil de volumen"}</label>{" "}<div className="grp"><span className="lbl">{"Área de valor"}</span><input type="range" id="vl-va" min="50" max="90" defaultValue="70" style={{"width":"110px"}} /><span className="val" id="vl-va-v">{"70%"}</span></div>{" "}<button className="btn" id="vl-new">{"Nuevo ejemplo"}</button>{" "}</div>{" "}<div className="chart-host" id="fig-vol" />{" "}<div className="legend"><span><i className="box" style={{"background":"var(--c-up)"}} />{"Volumen de vela alcista"}</span><span><i className="box" style={{"background":"var(--c-down)"}} />{"Volumen de vela bajista"}</span><span><i style={{"background":"var(--text-2)"}} />{"Media 20"}</span><span><i style={{"background":"var(--c-range)"}} />{"VWAP"}</span><span><i className="box" style={{"background":"var(--c-liq)"}} />{"POC"}</span></div>{" "}<div className="explain" id="vol-explain" />{" "}<details className="data" id="vol-data"><summary>{"Ver tabla de datos"}</summary></details>{" "}</div>{" "}<div className="rd-sentinel" data-l="vol-lab" /></article>
      <article className="lesson" id="vol-leer">{" "}<h3><span className="ln">{"8.3"}</span>{"Cómo leer el volumen"}</h3>{" "}<div className="prose">{" "}<ul><li><strong>{"Confirmación de rupturas:"}</strong>{" una ruptura con volumen muy por encima de su media suele tener continuidad; sin volumen, a menudo falla (prueba los dos primeros escenarios)."}</li><li><strong>{"Clímax / agotamiento:"}</strong>{" un pico de volumen extremo tras una caída larga, con mecha de rechazo, suele marcar capitulación: los últimos vendedores salen y los compradores absorben."}</li><li><strong>{"Divergencia de volumen:"}</strong>{" el precio sube pero cada impulso tiene menos volumen → menos participación, tendencia más frágil."}</li><li><strong>{"Relación con la liquidez:"}</strong>{" los barridos de liquidez suelen venir con picos de volumen (se ejecutan muchos stops a la vez)."}</li></ul>{" "}</div>{" "}<div className="rd-sentinel" data-l="vol-leer" /></article>
      <article className="lesson" id="vol-obv">{" "}<h3><span className="ln">{"8.4"}</span>{"OBV (On-Balance Volume)"}</h3>{" "}<div className="prose">{" "}<p>{"Popularizado por Joseph Granville (1963). Es un total acumulado: si la vela cierra por encima del cierre anterior se "}<strong>{"suma"}</strong>{" su volumen; si cierra por debajo, se "}<strong>{"resta"}</strong>{". La idea: el volumen precede al precio. Se usa para confirmar tendencias (OBV y precio subiendo juntos) y detectar divergencias (precio con máximo más alto y OBV sin superarlo). Actívalo en el laboratorio."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="vol-obv" /></article>
      <article className="lesson" id="vol-vwap">{" "}<h3><span className="ln">{"8.5"}</span>{"VWAP (precio medio ponderado por volumen)"}</h3>{" "}<div className="prose">{" "}<p><span className="mono">{"VWAP = Σ(precio típico × volumen) / Σ volumen"}</span>{", con precio típico = (máximo + mínimo + cierre) / 3, acumulado desde el inicio de la sesión (o desde una vela elegida: "}<strong>{"VWAP anclado"}</strong>{"). Es el \"precio justo\" del día para muchos institucionales: precio por encima del VWAP = compradores en control; por debajo = vendedores. Las bandas (desviaciones) marcan zonas estiradas."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="vol-vwap" /></article>
      <article className="lesson" id="vol-perfil">{" "}<h3><span className="ln">{"8.6"}</span>{"Perfil de volumen: POC y área de valor"}</h3>{" "}<div className="prose">{" "}<ul><li>{"El perfil reparte el volumen "}<strong>{"por niveles de precio"}</strong>{" (barras horizontales) en lugar de por tiempo."}</li><li><strong>{"POC"}</strong>{" (point of control): el precio con más volumen negociado. Actúa como imán."}</li><li><strong>{"Área de valor:"}</strong>{" el rango donde se negoció cerca del "}<strong>{"70%"}</strong>{" del volumen (algunos usan 68%). Sus bordes son "}<strong>{"VAH"}</strong>{" y "}<strong>{"VAL"}</strong>{"; fuera de ella el precio está \"caro\" o \"barato\"."}</li><li><strong>{"Nodos de alto/bajo volumen"}</strong>{" (HVN/LVN): el precio se frena en los altos y atraviesa rápido los bajos."}</li></ul>{" "}<p>{"Activa \"Perfil de volumen\" en el laboratorio y mueve el porcentaje del área de valor."}</p>{" "}</div>{" "}<div className="rd-sentinel" data-l="vol-perfil" /></article>
      <div id="volumen-quiz" />
    </>
  );
}
